export const DEMO_AGENCY = {
  name: 'World Tours Demo',
  companyName: 'World Tours Demo Agency',
  isVerified: true,
};

export const DEMO_TOURS = [
  {
    id: 'demo-1',
    agency_id: 'demo-agency',
    name: 'Santorini Sunset Cruise',
    slug: 'santorini-sunset-cruise',
    description: 'Sail around the caldera and watch the famous Santorini sunset from the water. Visit the volcanic hot springs, enjoy a freshly prepared Greek dinner on deck, and toast to the most photographed sunset in the Mediterranean.',
    country: 'Greece',
    city: 'Santorini',
    departure_country: 'Greece',
    departure_city: 'Athens',
    price: '189',
    currency: 'EUR',
    category: 'Cruise',
    duration_days: 3,
    max_participants: 20,
    start_date: new Date('2026-06-15'),
    end_date: new Date('2026-06-17'),
    contact_email: 'info@worldtoursdemo.com',
    contact_phone: '+30 210 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
    view_count: 0,
    favouriteCount: 0,
  },
  {
    id: 'demo-2',
    agency_id: 'demo-agency',
    name: 'Amalfi Coast Food & Wine Trail',
    slug: 'amalfi-coast-food-wine-trail',
    description: 'Taste your way along the stunning Amalfi Coast with local chefs and sommeliers. From fresh pasta workshops in Ravello to limoncello tasting in Positano, every meal is a celebration of Southern Italian cuisine.',
    country: 'Italy',
    city: 'Amalfi',
    departure_country: 'Italy',
    departure_city: 'Rome',
    price: '349',
    currency: 'EUR',
    category: 'Food & Wine',
    duration_days: 5,
    max_participants: 12,
    start_date: new Date('2026-07-01'),
    end_date: new Date('2026-07-05'),
    contact_email: 'info@worldtoursdemo.com',
    contact_phone: '+39 06 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
    view_count: 0,
    favouriteCount: 0,
  },
  {
    id: 'demo-3',
    agency_id: 'demo-agency',
    name: 'Kyoto Temple & Garden Walk',
    slug: 'kyoto-temple-garden-walk',
    description: 'Explore ancient temples, bamboo groves, and traditional tea houses in Kyoto. Walk the iconic Fushimi Inari shrine at dawn, experience a private tea ceremony, and discover hidden Zen gardens away from the crowds.',
    country: 'Japan',
    city: 'Kyoto',
    departure_country: 'Japan',
    departure_city: 'Tokyo',
    price: '275',
    currency: 'USD',
    category: 'Cultural',
    duration_days: 4,
    max_participants: 15,
    start_date: new Date('2026-04-10'),
    end_date: new Date('2026-04-13'),
    contact_email: 'info@worldtoursdemo.com',
    contact_phone: '+81 75 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
    view_count: 0,
    favouriteCount: 0,
  },
  {
    id: 'demo-4',
    agency_id: 'demo-agency',
    name: 'Atlas Mountains Trek',
    slug: 'atlas-mountains-trek',
    description: 'A challenging multi-day trek through the High Atlas with Berber village homestays. Summit Mount Toubkal, sleep under star-filled skies, and share mint tea with welcoming mountain families.',
    country: 'Morocco',
    city: 'Marrakech',
    departure_country: null,
    departure_city: null,
    price: '420',
    currency: 'EUR',
    category: 'Hiking & Trekking',
    duration_days: 7,
    max_participants: 10,
    start_date: new Date('2026-09-20'),
    end_date: new Date('2026-09-26'),
    contact_email: 'info@worldtoursdemo.com',
    contact_phone: '+212 524 123 456',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
    view_count: 0,
    favouriteCount: 0,
  },
  {
    id: 'demo-5',
    agency_id: 'demo-agency',
    name: 'Bali Wellness Retreat',
    slug: 'bali-wellness-retreat',
    description: 'Rejuvenate with yoga, spa treatments, and organic cuisine in the heart of Ubud. Practice sunrise yoga overlooking rice terraces, indulge in traditional Balinese healing rituals, and find your inner balance.',
    country: 'Indonesia',
    city: 'Ubud',
    departure_country: 'Indonesia',
    departure_city: 'Jakarta',
    price: '599',
    currency: 'USD',
    category: 'Wellness & Spa',
    duration_days: 6,
    max_participants: 8,
    start_date: new Date('2026-05-01'),
    end_date: new Date('2026-05-06'),
    contact_email: 'info@worldtoursdemo.com',
    contact_phone: '+62 361 123 456',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
    view_count: 0,
    favouriteCount: 0,
  },
  // Africa
  {
    id: 'demo-6',
    agency_id: 'demo-agency',
    name: 'Serengeti Safari Adventure',
    slug: 'serengeti-safari-adventure',
    description: 'Witness the Great Migration and spot the Big Five on an unforgettable safari through the Serengeti. Stay in luxury tented camps, enjoy sundowner cocktails on the savanna, and wake up to the sounds of the African bush.',
    country: 'Tanzania',
    city: 'Serengeti',
    departure_country: 'Tanzania',
    departure_city: 'Arusha',
    price: '2450',
    currency: 'USD',
    category: 'Wildlife',
    duration_days: 8,
    max_participants: 12,
    start_date: new Date('2026-07-10'),
    end_date: new Date('2026-07-17'),
    contact_email: 'safari@worldtoursdemo.com',
    contact_phone: '+255 27 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-7',
    agency_id: 'demo-agency',
    name: 'Nile River Cruise',
    slug: 'nile-river-cruise',
    description: 'Cruise the ancient Nile from Luxor to Aswan aboard a traditional felucca. Visit the Valley of the Kings, Karnak Temple, and the Temple of Philae while floating through 5,000 years of history.',
    country: 'Egypt',
    city: 'Luxor',
    departure_country: 'Egypt',
    departure_city: 'Cairo',
    price: '1200',
    currency: 'USD',
    category: 'Cruise',
    duration_days: 7,
    max_participants: 24,
    start_date: new Date('2026-10-05'),
    end_date: new Date('2026-10-11'),
    contact_email: 'nile@worldtoursdemo.com',
    contact_phone: '+20 2 1234 5678',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1539768942893-daf53e736b68?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-8',
    agency_id: 'demo-agency',
    name: 'Cape Town Wine Trail',
    slug: 'cape-town-wine-trail',
    description: 'Explore the world-renowned Cape Winelands with expert sommeliers. Visit Stellenbosch, Franschhoek, and Paarl estates, paired with gourmet South African cuisine and breathtaking mountain views.',
    country: 'South Africa',
    city: 'Cape Town',
    departure_country: 'South Africa',
    departure_city: 'Johannesburg',
    price: '680',
    currency: 'USD',
    category: 'Food & Wine',
    duration_days: 4,
    max_participants: 10,
    start_date: new Date('2026-03-15'),
    end_date: new Date('2026-03-18'),
    contact_email: 'wine@worldtoursdemo.com',
    contact_phone: '+27 21 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  // South America
  {
    id: 'demo-9',
    agency_id: 'demo-agency',
    name: 'Machu Picchu Trek',
    slug: 'machu-picchu-trek',
    description: 'Hike the legendary Inca Trail to the lost city of Machu Picchu. Four days through cloud forests, Inca ruins, and mountain passes culminating in a sunrise arrival at one of the New Seven Wonders of the World.',
    country: 'Peru',
    city: 'Cusco',
    departure_country: 'Peru',
    departure_city: 'Lima',
    price: '890',
    currency: 'USD',
    category: 'Hiking & Trekking',
    duration_days: 5,
    max_participants: 16,
    start_date: new Date('2026-06-01'),
    end_date: new Date('2026-06-05'),
    contact_email: 'andes@worldtoursdemo.com',
    contact_phone: '+51 84 123 456',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1587595431973-160d0d163571?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-10',
    agency_id: 'demo-agency',
    name: 'Patagonia Photography Expedition',
    slug: 'patagonia-photography-expedition',
    description: 'Capture the dramatic landscapes of Patagonia with a professional photographer guide. From the granite spires of Torres del Paine to massive glaciers and turquoise lakes, every frame is a masterpiece.',
    country: 'Argentina',
    city: 'El Calafate',
    departure_country: 'Argentina',
    departure_city: 'Buenos Aires',
    price: '1750',
    currency: 'USD',
    category: 'Photography',
    duration_days: 9,
    max_participants: 8,
    start_date: new Date('2026-11-10'),
    end_date: new Date('2026-11-18'),
    contact_email: 'patagonia@worldtoursdemo.com',
    contact_phone: '+54 11 1234 5678',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1531761535209-180857e963b9?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-11',
    agency_id: 'demo-agency',
    name: 'Amazon Rainforest Expedition',
    slug: 'amazon-rainforest-expedition',
    description: 'Venture deep into the Amazon basin for an immersive jungle experience. Spot exotic wildlife, canoe through flooded forests, visit indigenous communities, and sleep in a treehouse lodge above the canopy.',
    country: 'Brazil',
    city: 'Manaus',
    departure_country: 'Brazil',
    departure_city: 'São Paulo',
    price: '1100',
    currency: 'USD',
    category: 'Adventure',
    duration_days: 6,
    max_participants: 10,
    start_date: new Date('2026-08-05'),
    end_date: new Date('2026-08-10'),
    contact_email: 'amazon@worldtoursdemo.com',
    contact_phone: '+55 92 1234 5678',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  // North America
  {
    id: 'demo-12',
    agency_id: 'demo-agency',
    name: 'Grand Canyon Expedition',
    slug: 'grand-canyon-expedition',
    description: 'Raft the Colorado River through the heart of the Grand Canyon. Experience Class III-IV rapids, hike to hidden waterfalls, camp under the stars on sandy beaches, and explore one of Earth\'s most awe-inspiring landscapes.',
    country: 'USA',
    city: 'Grand Canyon',
    departure_country: 'USA',
    departure_city: 'Las Vegas',
    price: '1850',
    currency: 'USD',
    category: 'Adventure',
    duration_days: 7,
    max_participants: 16,
    start_date: new Date('2026-05-20'),
    end_date: new Date('2026-05-26'),
    contact_email: 'canyon@worldtoursdemo.com',
    contact_phone: '+1 928 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-13',
    agency_id: 'demo-agency',
    name: 'NYC Food Tour',
    slug: 'nyc-food-tour',
    description: 'Eat your way through New York City\'s most iconic neighborhoods. From Chinatown dumplings to Brooklyn pizza, Little Italy cannoli to Harlem soul food — experience the world on one plate at a time.',
    country: 'USA',
    city: 'New York',
    departure_country: 'USA',
    departure_city: 'New York',
    price: '159',
    currency: 'USD',
    category: 'City Tours',
    duration_days: 2,
    max_participants: 12,
    start_date: new Date('2026-04-15'),
    end_date: new Date('2026-04-16'),
    contact_email: 'nyc@worldtoursdemo.com',
    contact_phone: '+1 212 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-14',
    agency_id: 'demo-agency',
    name: 'Banff Wildlife Safari',
    slug: 'banff-wildlife-safari',
    description: 'Spot grizzly bears, elk, and wolves in the Canadian Rockies. Guided wildlife viewing in Banff and Jasper National Parks with stunning mountain scenery, turquoise lakes, and pristine wilderness.',
    country: 'Canada',
    city: 'Banff',
    departure_country: 'Canada',
    departure_city: 'Calgary',
    price: '980',
    currency: 'USD',
    category: 'Wildlife',
    duration_days: 5,
    max_participants: 10,
    start_date: new Date('2026-06-20'),
    end_date: new Date('2026-06-24'),
    contact_email: 'banff@worldtoursdemo.com',
    contact_phone: '+1 403 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  // Europe
  {
    id: 'demo-15',
    agency_id: 'demo-agency',
    name: 'Northern Lights Chase',
    slug: 'northern-lights-chase',
    description: 'Chase the Aurora Borealis across Iceland\'s dramatic landscapes. Visit geysers, waterfalls, and black sand beaches by day, then hunt for the Northern Lights by night with expert guides and photographers.',
    country: 'Iceland',
    city: 'Reykjavik',
    departure_country: 'Iceland',
    departure_city: 'Reykjavik',
    price: '1350',
    currency: 'EUR',
    category: 'Nature',
    duration_days: 5,
    max_participants: 14,
    start_date: new Date('2026-10-15'),
    end_date: new Date('2026-10-19'),
    contact_email: 'iceland@worldtoursdemo.com',
    contact_phone: '+354 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-16',
    agency_id: 'demo-agency',
    name: 'Barcelona Architecture Walk',
    slug: 'barcelona-architecture-walk',
    description: 'Discover Gaudí\'s masterpieces and Barcelona\'s architectural treasures with an expert historian. From the Sagrada Família to Park Güell, explore the genius of Modernisme and the Gothic Quarter\'s medieval charm.',
    country: 'Spain',
    city: 'Barcelona',
    departure_country: 'Spain',
    departure_city: 'Madrid',
    price: '225',
    currency: 'EUR',
    category: 'Cultural',
    duration_days: 3,
    max_participants: 15,
    start_date: new Date('2026-05-10'),
    end_date: new Date('2026-05-12'),
    contact_email: 'barcelona@worldtoursdemo.com',
    contact_phone: '+34 93 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-17',
    agency_id: 'demo-agency',
    name: 'Dubrovnik Coastal Cruise',
    slug: 'dubrovnik-coastal-cruise',
    description: 'Sail the crystal-clear Adriatic along Croatia\'s stunning Dalmatian Coast. Island-hop between Hvar, Korčula, and Mljet, swim in secluded coves, and explore Dubrovnik\'s ancient walls at sunset.',
    country: 'Croatia',
    city: 'Dubrovnik',
    departure_country: 'Croatia',
    departure_city: 'Split',
    price: '950',
    currency: 'EUR',
    category: 'Cruise',
    duration_days: 7,
    max_participants: 18,
    start_date: new Date('2026-07-15'),
    end_date: new Date('2026-07-21'),
    contact_email: 'croatia@worldtoursdemo.com',
    contact_phone: '+385 20 123 456',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1555990538-1e15c8a45797?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-18',
    agency_id: 'demo-agency',
    name: 'Paris Photography Walk',
    slug: 'paris-photography-walk',
    description: 'Capture Paris through your lens with a professional photographer guide. From golden-hour shots at the Eiffel Tower to hidden passages of Montmartre, learn composition and storytelling in the City of Light.',
    country: 'France',
    city: 'Paris',
    departure_country: 'France',
    departure_city: 'Paris',
    price: '195',
    currency: 'EUR',
    category: 'Photography',
    duration_days: 2,
    max_participants: 8,
    start_date: new Date('2026-09-05'),
    end_date: new Date('2026-09-06'),
    contact_email: 'paris@worldtoursdemo.com',
    contact_phone: '+33 1 1234 5678',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-19',
    agency_id: 'demo-agency',
    name: 'Algarve Beach Hopping',
    slug: 'algarve-beach-hopping',
    description: 'Discover Portugal\'s most stunning coastline — golden cliffs, hidden sea caves, and turquoise waters. Kayak through the Benagil Cave, surf in Sagres, and relax on Europe\'s most beautiful beaches.',
    country: 'Portugal',
    city: 'Lagos',
    departure_country: 'Portugal',
    departure_city: 'Lisbon',
    price: '475',
    currency: 'EUR',
    category: 'Beach & Island',
    duration_days: 5,
    max_participants: 12,
    start_date: new Date('2026-06-10'),
    end_date: new Date('2026-06-14'),
    contact_email: 'algarve@worldtoursdemo.com',
    contact_phone: '+351 282 123 456',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  // Asia
  {
    id: 'demo-20',
    agency_id: 'demo-agency',
    name: 'Kerala Backwaters Retreat',
    slug: 'kerala-backwaters-retreat',
    description: 'Drift through Kerala\'s serene backwaters on a traditional houseboat. Experience Ayurvedic treatments, taste fresh Kerala cuisine, and watch the sunset over palm-fringed lagoons in God\'s Own Country.',
    country: 'India',
    city: 'Alleppey',
    departure_country: 'India',
    departure_city: 'Kochi',
    price: '450',
    currency: 'USD',
    category: 'Wellness & Spa',
    duration_days: 5,
    max_participants: 8,
    start_date: new Date('2026-11-01'),
    end_date: new Date('2026-11-05'),
    contact_email: 'kerala@worldtoursdemo.com',
    contact_phone: '+91 484 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-21',
    agency_id: 'demo-agency',
    name: 'Ha Long Bay Cruise',
    slug: 'ha-long-bay-cruise',
    description: 'Cruise among thousands of limestone karsts and islands in Ha Long Bay. Kayak through emerald waters, explore hidden caves, enjoy fresh Vietnamese seafood on deck, and wake up to misty morning views.',
    country: 'Vietnam',
    city: 'Ha Long',
    departure_country: 'Vietnam',
    departure_city: 'Hanoi',
    price: '380',
    currency: 'USD',
    category: 'Cruise',
    duration_days: 3,
    max_participants: 20,
    start_date: new Date('2026-04-20'),
    end_date: new Date('2026-04-22'),
    contact_email: 'vietnam@worldtoursdemo.com',
    contact_phone: '+84 24 1234 5678',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-22',
    agency_id: 'demo-agency',
    name: 'Bangkok Street Food Safari',
    slug: 'bangkok-street-food-safari',
    description: 'Dive into Bangkok\'s legendary street food scene with a local foodie guide. From Michelin-starred market stalls to secret family-run noodle shops, taste the incredible diversity of Thai cuisine one bite at a time.',
    country: 'Thailand',
    city: 'Bangkok',
    departure_country: 'Thailand',
    departure_city: 'Bangkok',
    price: '95',
    currency: 'USD',
    category: 'Food & Wine',
    duration_days: 1,
    max_participants: 10,
    start_date: new Date('2026-03-20'),
    end_date: new Date('2026-03-20'),
    contact_email: 'bangkok@worldtoursdemo.com',
    contact_phone: '+66 2 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-23',
    agency_id: 'demo-agency',
    name: 'Seoul Cultural Immersion',
    slug: 'seoul-cultural-immersion',
    description: 'Experience the perfect blend of ancient tradition and K-culture in Seoul. Visit centuries-old palaces, learn to make kimchi, explore vibrant Hongdae, and discover the stories behind Korea\'s cultural renaissance.',
    country: 'South Korea',
    city: 'Seoul',
    departure_country: 'South Korea',
    departure_city: 'Seoul',
    price: '320',
    currency: 'USD',
    category: 'Cultural',
    duration_days: 4,
    max_participants: 14,
    start_date: new Date('2026-10-01'),
    end_date: new Date('2026-10-04'),
    contact_email: 'seoul@worldtoursdemo.com',
    contact_phone: '+82 2 1234 5678',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  // Oceania
  {
    id: 'demo-24',
    agency_id: 'demo-agency',
    name: 'Great Barrier Reef Discovery',
    slug: 'great-barrier-reef-discovery',
    description: 'Snorkel and dive the world\'s largest coral reef system. Swim with sea turtles, spot clownfish in vibrant coral gardens, and sail to the outer reef for an experience that will take your breath away.',
    country: 'Australia',
    city: 'Cairns',
    departure_country: 'Australia',
    departure_city: 'Sydney',
    price: '1200',
    currency: 'USD',
    category: 'Beach & Island',
    duration_days: 5,
    max_participants: 16,
    start_date: new Date('2026-08-15'),
    end_date: new Date('2026-08-19'),
    contact_email: 'reef@worldtoursdemo.com',
    contact_phone: '+61 7 1234 5678',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1587139223877-04cb899fa3e8?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-25',
    agency_id: 'demo-agency',
    name: 'Queenstown Adventure Week',
    slug: 'queenstown-adventure-week',
    description: 'The adventure capital of the world lives up to its name. Bungee jump, skydive, jet boat, hike the Routeburn Track, and explore Milford Sound — all against the backdrop of New Zealand\'s Southern Alps.',
    country: 'New Zealand',
    city: 'Queenstown',
    departure_country: 'New Zealand',
    departure_city: 'Auckland',
    price: '1650',
    currency: 'USD',
    category: 'Adventure',
    duration_days: 7,
    max_participants: 12,
    start_date: new Date('2026-12-01'),
    end_date: new Date('2026-12-07'),
    contact_email: 'nz@worldtoursdemo.com',
    contact_phone: '+64 3 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-26',
    agency_id: 'demo-agency',
    name: 'Fiji Island Hopping',
    slug: 'fiji-island-hopping',
    description: 'Island-hop through Fiji\'s pristine archipelago. Snorkel in crystal-clear lagoons, relax on white sand beaches, visit traditional villages, and experience the legendary Fijian hospitality — Bula!',
    country: 'Fiji',
    city: 'Nadi',
    departure_country: 'Fiji',
    departure_city: 'Nadi',
    price: '1400',
    currency: 'USD',
    category: 'Beach & Island',
    duration_days: 8,
    max_participants: 10,
    start_date: new Date('2026-09-10'),
    end_date: new Date('2026-09-17'),
    contact_email: 'fiji@worldtoursdemo.com',
    contact_phone: '+679 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  // Middle East
  {
    id: 'demo-27',
    agency_id: 'demo-agency',
    name: 'Petra & Wadi Rum Explorer',
    slug: 'petra-wadi-rum-explorer',
    description: 'Walk through the ancient rose-red city of Petra and camp under the stars in Wadi Rum\'s Martian desert. Ride camels through sandstone canyons, explore Nabataean tombs, and float in the Dead Sea.',
    country: 'Jordan',
    city: 'Petra',
    departure_country: 'Jordan',
    departure_city: 'Amman',
    price: '780',
    currency: 'USD',
    category: 'Historical',
    duration_days: 5,
    max_participants: 14,
    start_date: new Date('2026-04-01'),
    end_date: new Date('2026-04-05'),
    contact_email: 'jordan@worldtoursdemo.com',
    contact_phone: '+962 6 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1579606032821-4e6161c81571?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
  {
    id: 'demo-28',
    agency_id: 'demo-agency',
    name: 'Dubai Desert Safari',
    slug: 'dubai-desert-safari',
    description: 'Experience the thrill of dune bashing, sandboarding, and camel riding in the Arabian desert. End the day with a traditional Bedouin camp dinner under the stars with live entertainment and henna painting.',
    country: 'UAE',
    city: 'Dubai',
    departure_country: 'UAE',
    departure_city: 'Dubai',
    price: '120',
    currency: 'USD',
    category: 'Adventure',
    duration_days: 1,
    max_participants: 20,
    start_date: new Date('2026-11-15'),
    end_date: new Date('2026-11-15'),
    contact_email: 'dubai@worldtoursdemo.com',
    contact_phone: '+971 4 123 4567',
    contact_website: 'https://worldtoursdemo.com',
    status: 'active',
    stripe_payment_id: null,
    created_at: new Date(),
    updated_at: new Date(),
    images: [],
    thumbnail: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=600&h=400&fit=crop',
    rating: 0,
    review_count: 0,
    booking_count: 0,
  },
];

// Curated 6 featured tours — diverse destinations and categories
export const FEATURED_TOURS = [
  DEMO_TOURS[0],  // Santorini Sunset Cruise (Europe)
  DEMO_TOURS[5],  // Serengeti Safari (Africa)
  DEMO_TOURS[8],  // Machu Picchu Trek (South America)
  DEMO_TOURS[14], // Northern Lights Chase (Iceland)
  DEMO_TOURS[23], // Great Barrier Reef (Oceania)
  DEMO_TOURS[4],  // Bali Wellness Retreat (Asia)
];

export function getDemoTourBySlug(slug: string) {
  return DEMO_TOURS.find((t) => t.slug === slug);
}

export const DEMO_REVIEWS: Record<string, { name: string; rating: number; text: string; date: string }[]> = {
  'santorini-sunset-cruise': [
    { name: 'Sarah M.', rating: 5, text: 'Absolutely magical! The sunset was even more beautiful from the water. The crew was incredibly attentive and the dinner was delicious.', date: '2025-09-12' },
    { name: 'James K.', rating: 5, text: 'Best experience of our honeymoon. The hot springs stop was a great bonus. Highly recommend the premium wine package.', date: '2025-08-28' },
    { name: 'Elena P.', rating: 4, text: 'Beautiful cruise with great views. Only wish it was a bit longer! The caldera views at sunset were absolutely stunning.', date: '2025-07-15' },
  ],
  'amalfi-coast-food-wine-trail': [
    { name: 'Marco R.', rating: 5, text: 'As an Italian food lover, this exceeded all expectations. The limoncello tasting in Positano was a highlight. Every meal was a masterpiece.', date: '2025-10-02' },
    { name: 'Linda W.', rating: 5, text: 'Our guide knew every hidden gem along the coast. The pasta-making workshop was so much fun — I still make the recipes at home!', date: '2025-09-20' },
  ],
  'kyoto-temple-garden-walk': [
    { name: 'David L.', rating: 5, text: 'The private tea ceremony was an unforgettable experience. Our guide shared stories and context that brought every temple to life.', date: '2025-05-18' },
    { name: 'Yuki T.', rating: 4, text: 'As a local, I was skeptical, but this tour showed me hidden spots in Kyoto I never knew existed. The bamboo grove at dawn was peaceful and empty.', date: '2025-04-30' },
    { name: 'Rachel B.', rating: 5, text: 'Cherry blossom season made this tour absolutely magical. The guide timed everything perfectly to avoid crowds.', date: '2025-04-12' },
  ],
  'atlas-mountains-trek': [
    { name: 'Tom H.', rating: 5, text: 'Challenging but incredibly rewarding. The Berber homestay was a genuine cultural experience. Our guide was strong and knowledgeable.', date: '2025-10-15' },
    { name: 'Amina B.', rating: 4, text: 'The mountain scenery was breathtaking. Pack warm layers for the summit night — it gets cold! The mint tea at every village was a wonderful tradition.', date: '2025-09-28' },
  ],
  'bali-wellness-retreat': [
    { name: 'Jessica P.', rating: 5, text: 'This retreat changed my life. The sunrise yoga overlooking the rice terraces was pure magic. I left feeling completely renewed.', date: '2025-06-22' },
    { name: 'Michael C.', rating: 5, text: 'Perfect balance of activities and relaxation. The Balinese healing session was profound. The organic food was incredible too.', date: '2025-05-30' },
    { name: 'Sophie L.', rating: 4, text: 'Beautiful location and wonderful staff. The daily schedule was well-paced. I appreciated having free time to explore Ubud on my own.', date: '2025-05-15' },
  ],
  'serengeti-safari-adventure': [
    { name: 'Robert K.', rating: 5, text: 'Saw all of the Big Five in one day! The Great Migration was beyond words. Our guide had incredible eyesight for spotting wildlife.', date: '2025-08-10' },
    { name: 'Patricia N.', rating: 5, text: 'The tented camp was pure luxury in the middle of the wilderness. Waking up to zebras outside our tent was surreal.', date: '2025-07-22' },
    { name: 'George M.', rating: 5, text: 'A once-in-a-lifetime experience. The sundowner cocktails on the savanna with a view of Mount Kilimanjaro — no words.', date: '2025-08-05' },
  ],
  'machu-picchu-trek': [
    { name: 'Carlos V.', rating: 5, text: 'The sunrise arrival at Machu Picchu through the Sun Gate was the most emotional moment of my travels. Worth every step.', date: '2025-07-10' },
    { name: 'Emma S.', rating: 5, text: 'Our porters and guide were amazing. The cloud forest section was surprisingly beautiful. Book early — permits sell out fast!', date: '2025-06-28' },
  ],
  'northern-lights-chase': [
    { name: 'Anna F.', rating: 5, text: 'We saw the Northern Lights on three out of four nights! The guide knew exactly where to go. Iceland\'s landscapes are otherworldly.', date: '2025-11-12' },
    { name: 'Henrik S.', rating: 4, text: 'Even without guaranteed aurora sightings, the tour was fantastic. The waterfalls and geysers alone were worth it.', date: '2025-10-28' },
  ],
  'grand-canyon-expedition': [
    { name: 'Mike T.', rating: 5, text: 'Rafting the Colorado was the adventure of a lifetime. The hidden waterfalls and camping on beaches under the stars — absolutely incredible.', date: '2025-06-15' },
    { name: 'Laura G.', rating: 5, text: 'The scale of the Grand Canyon from the river is something photos can never capture. Our guides were experts and great storytellers.', date: '2025-05-30' },
  ],
  'ha-long-bay-cruise': [
    { name: 'Thanh N.', rating: 5, text: 'The misty morning views from the deck were like a painting. The kayaking through caves was an amazing experience. Fresh seafood was delicious!', date: '2025-05-20' },
    { name: 'Claire D.', rating: 4, text: 'Beautiful scenery and comfortable boat. The cooking class was a fun surprise. Wish we had more time at some of the islands.', date: '2025-04-28' },
  ],
  'petra-wadi-rum-explorer': [
    { name: 'Ali M.', rating: 5, text: 'Walking through the Siq and seeing the Treasury for the first time gave me chills. Sleeping under the stars in Wadi Rum was magical.', date: '2025-05-01' },
    { name: 'Katherine R.', rating: 5, text: 'Jordan exceeded all expectations. The Dead Sea float was hilarious and the Bedouin camp dinner was the most memorable meal of the trip.', date: '2025-04-15' },
  ],
  'great-barrier-reef-discovery': [
    { name: 'Chris W.', rating: 5, text: 'Swimming with sea turtles was a dream come true. The reef is even more colorful than photos suggest. An experience I\'ll never forget.', date: '2025-09-10' },
    { name: 'Olivia H.', rating: 4, text: 'Great reef experience. The crew was knowledgeable about marine life. Snorkeling gear was provided and of good quality.', date: '2025-08-25' },
  ],
  'dubai-desert-safari': [
    { name: 'Fatima A.', rating: 4, text: 'The dune bashing was thrilling! The sunset over the desert was gorgeous. The camp dinner and entertainment were fun and well-organized.', date: '2025-12-05' },
    { name: 'Steve J.', rating: 5, text: 'Great value for money. The sandboarding was my favorite part. The Bedouin camp under the stars was a perfect way to end the evening.', date: '2025-11-20' },
  ],
  'queenstown-adventure-week': [
    { name: 'Ben T.', rating: 5, text: 'Bungee jumping off the Kawarau Bridge was terrifying and exhilarating. Every single day was packed with incredible experiences.', date: '2026-01-15' },
    { name: 'Megan P.', rating: 5, text: 'Milford Sound was breathtaking. The skydive over Queenstown with mountain views was the highlight. Best adventure week of my life!', date: '2026-01-08' },
  ],
  'barcelona-architecture-walk': [
    { name: 'Isabel G.', rating: 5, text: 'Our guide brought Gaudí\'s genius to life with incredible stories. Seeing the Sagrada Família with an expert by your side is a completely different experience.', date: '2025-06-20' },
    { name: 'Paul D.', rating: 4, text: 'Learned so much about Modernisme I never knew. The Gothic Quarter walk was a highlight. Great small group size.', date: '2025-06-05' },
  ],
  'bangkok-street-food-safari': [
    { name: 'Niran P.', rating: 5, text: 'Our guide took us to places we\'d never find on our own. The pad thai at the Michelin-starred street stall was life-changing. Come hungry!', date: '2025-04-10' },
    { name: 'Amy L.', rating: 5, text: 'Best food tour I\'ve ever done anywhere in the world. We tried at least 15 different dishes. The mango sticky rice was the perfect ending.', date: '2025-03-25' },
  ],
  'nyc-food-tour': [
    { name: 'Dan R.', rating: 4, text: 'Great way to experience NYC\'s food diversity. The Chinatown stop was my favorite. Wear comfortable shoes — lots of walking!', date: '2025-05-12' },
    { name: 'Maria S.', rating: 5, text: 'Our guide was a born-and-raised New Yorker who knew all the best spots. The Brooklyn pizza was the best I\'ve ever had.', date: '2025-04-28' },
  ],
  'patagonia-photography-expedition': [
    { name: 'Carlos M.', rating: 5, text: 'The photography coaching was invaluable. Seeing Torres del Paine at sunrise through my camera was indescribable. My portfolio is transformed.', date: '2025-12-20' },
    { name: 'Julia K.', rating: 5, text: 'Small group, expert guide, jaw-dropping landscapes. The glacier shots alone were worth the trip. A photographer\'s paradise.', date: '2025-12-10' },
  ],
  'amazon-rainforest-expedition': [
    { name: 'Pedro S.', rating: 4, text: 'Incredible biodiversity — spotted pink dolphins, macaws, and a sloth! The treehouse lodge was an adventure in itself. Bug spray is a must.', date: '2025-09-15' },
    { name: 'Nina H.', rating: 5, text: 'The indigenous village visit was respectful and genuinely educational. Night jungle walk was exciting. An unforgettable experience.', date: '2025-08-30' },
  ],
  'cape-town-wine-trail': [
    { name: 'Johan V.', rating: 5, text: 'The Stellenbosch wineries were stunning. Our sommelier guide made the tastings so much more engaging. The cheese pairing was a highlight.', date: '2025-04-20' },
    { name: 'Diana K.', rating: 4, text: 'Beautiful scenery and excellent wines. The Franschhoek lunch was gourmet quality. Would love a longer tour to see more estates.', date: '2025-03-30' },
  ],
  'fiji-island-hopping': [
    { name: 'Matt B.', rating: 5, text: 'Paradise found! Each island had its own unique charm. The village kava ceremony was a moving experience. The snorkeling was world-class.', date: '2025-10-12' },
    { name: 'Lisa W.', rating: 4, text: 'Relaxing and beautiful. The Fijian people are the warmest hosts you\'ll ever meet. The beach BBQ dinner was a perfect evening.', date: '2025-09-28' },
  ],
  'seoul-cultural-immersion': [
    { name: 'Jiyeon K.', rating: 5, text: 'As a K-culture fan, this was a dream. The kimchi-making class and palace visits were highlights. The guide explained modern Korean culture so well.', date: '2025-11-05' },
    { name: 'Ryan T.', rating: 4, text: 'Great mix of traditional and modern Seoul. Hongdae nightlife and Bukchon Hanok Village were both fantastic. The food throughout was excellent.', date: '2025-10-20' },
  ],
  'kerala-backwaters-retreat': [
    { name: 'Priya S.', rating: 5, text: 'The houseboat experience was incredibly peaceful. Drifting through the backwaters at sunset with fresh Kerala fish curry — heavenly.', date: '2025-12-10' },
    { name: 'Mark H.', rating: 4, text: 'The Ayurvedic treatments were therapeutic and the staff was knowledgeable. A truly restorative experience in beautiful surroundings.', date: '2025-11-25' },
  ],
  'algarve-beach-hopping': [
    { name: 'Sofia C.', rating: 5, text: 'The Benagil Cave kayak trip was absolutely worth it. Every beach was more beautiful than the last. The Algarve is Europe\'s best-kept secret.', date: '2025-07-15' },
    { name: 'Thomas B.', rating: 4, text: 'Perfect summer tour. The surf lesson in Sagres was a bonus highlight. Great balance of adventure and relaxation on stunning beaches.', date: '2025-07-02' },
  ],
  'paris-photography-walk': [
    { name: 'Camille D.', rating: 5, text: 'Learned more about composition in two days than in months of tutorials. The golden hour Eiffel Tower shots are now my prized possessions.', date: '2025-10-08' },
    { name: 'Brian M.', rating: 4, text: 'Great tour for photography enthusiasts. The hidden passages of Montmartre were a revelation. Small group size meant lots of personal attention.', date: '2025-09-22' },
  ],
  'nile-river-cruise': [
    { name: 'Hassan E.', rating: 5, text: 'Floating through 5,000 years of history was surreal. The Temple of Karnak at night was breathtaking. An Egyptologist\'s dream tour.', date: '2025-11-18' },
    { name: 'Wendy P.', rating: 4, text: 'Comfortable boat and excellent guide. The Valley of the Kings was awe-inspiring. Morning views from the deck were beautiful.', date: '2025-10-30' },
  ],
  'banff-wildlife-safari': [
    { name: 'Tyler C.', rating: 5, text: 'Spotted a grizzly bear with cubs on day one! Lake Louise was even more beautiful in person. Our guide knew every trail and viewpoint.', date: '2025-07-20' },
    { name: 'Emily R.', rating: 4, text: 'The Canadian Rockies are stunning. Great wildlife viewing guides. The elk sighting at dusk was a magical moment.', date: '2025-07-08' },
  ],
  'dubrovnik-coastal-cruise': [
    { name: 'Ivan M.', rating: 5, text: 'Croatia from the water is breathtaking. Swimming in secluded coves and exploring Hvar\'s lavender fields were trip highlights.', date: '2025-08-15' },
    { name: 'Natalie F.', rating: 4, text: 'Perfect way to see the Dalmatian Coast. Dubrovnik\'s walls at sunset were stunning. The fresh seafood on the boat was excellent.', date: '2025-08-02' },
  ],
};
